DROP TABLE IF EXISTS event_responses;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS group_comments;
DROP TABLE IF EXISTS group_posts;
DROP TABLE IF EXISTS group_members;
DROP TABLE IF EXISTS groups;